name: spotify_explorer
channels:
  - defaults
dependencies:
  - numpy=1.19.2
  - pandas=1.1.5
  - pip=21.2.2
  - plotly=5.1.0
  - pyarrow=4.0.1
  - yaml=0.2.5
  - pip:
    - spotipy==2.19.0
    - streamlit==1.3.1
    